import Head from 'next/head'
import styles from '../styles/Home.module.css'
import {BlogNav} from "../components/Layout/BlogNav";
import React from "react";
import {Motion} from "../components/Motion";


export default function Home() {
    return (
        <div className={`body`}>
            <div>
                <Head>
                    <title>2021 Q1 Blog</title>
                    <meta name="description" content="Generated by create next app"/>
                    <link rel="icon" href="/favicon.ico"/>
                    <meta
                        name="viewport"
                        content="initial-scale=1.0, width=device-width"
                    />
                    <link
                        rel="stylesheet"
                        href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/css/bootstrap.min.css"
                        integrity="sha384-Zug+QiDoJOrZ5t4lssLdxGhVrurbmBWopoEl+M6BdEfwnCJZtKxi1KgxUyJq13dy"
                        crossOrigin="anonymous"
                    />
                    <style>{`
            .page {
              height: 100vh;
            }
          `}</style>
                </Head>

                <div id="wrapper">
                    <h1 className={styles.title}>
                        Welcome to <a
                        href="https://www.youtube.com/watch?v=QgPriWpnMWM&list=PLgZszgjqISjYCCie4kUkclMr5dwMsci-0">2021
                        Q2</a>
                    </h1>
                    <Motion>
                        <header id="header">

                            <div className="logo">
                                <span className="icon fa-diamond"></span>
                            </div>
                            <div className="content">
                                <div className="inner">
                                    <h1>2021 Q1 Blog</h1>
                                    <p className={styles.description}>

                                        <code className={styles.code}>Explore 2021 Q1 hot features</code>
                                    </p>

                                </div>
                            </div>

                            <BlogNav/>
                        </header>
                    </Motion>

                </div>

                <footer className={styles.footer}>
                    Powered by{' '}
                </footer>
                <div id="bg"/>
            </div>
        </div>
    )
}
