import Head from 'next/head'
import styles from '../styles/Home.module.css'
import {BlogNav} from "../components/Layout/BlogNav";
import dynamic from "next/dynamic";
import React from "react";
import faGem from "@fortawesome/fontawesome-free-regular/faGem";

export default function Home() {
    return (
        <div className={styles.container}>
            <Head>
                <title>2021 Q1 Blog</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
                <meta
                    name="viewport"
                    content="initial-scale=1.0, width=device-width"
                />
                <link
                    rel="stylesheet"
                    href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/css/bootstrap.min.css"
                    integrity="sha384-Zug+QiDoJOrZ5t4lssLdxGhVrurbmBWopoEl+M6BdEfwnCJZtKxi1KgxUyJq13dy"
                    crossOrigin="anonymous"
                />
                <style>{`
            .page {
              height: 100vh;
            }
          `}</style>
            </Head>


            <main className={styles.main}>

                <h1 className={styles.title}>
                    Welcome to <a href="https://nextjs.org">2021 Q2</a>
                </h1>

                <header id="header">
                    <div className="logo">
                        <span className="icon fa-diamond"></span>
                    </div>
                    <div className="content">
                        <div className="inner">
                            <h1>2021 Q1 Blog</h1>
                            <p className={styles.description}>

                                <code className={styles.code}>Explore 2021 Q1 hot features</code>
                            </p>
                            <faGem/>
                        </div>
                    </div>
                    <BlogNav/>
                </header>

            </main>

            <footer className={styles.footer}>
                <a
                    href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Powered by{' '}
                    <span className={styles.logo}>
            <img src="/vercel.svg" alt="Vercel Logo" width={72} height={16}/>
          </span>
                </a>
            </footer>
        </div>
    )
}
